development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: test_house
  pool: 50
  username: root
  password: wasq12
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: test_house
  pool: 5
  username: root
  password: wasq12
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: test_house
  pool: 5
  host: localhost
  username: root
  password: wasq12
  socket: /var/run/mysqld/mysqld.sock
